# Change these first
owner: Cpluz # Your GitHub organization or username, where this repository lives
repo: sitecheck # The name of this repository

sites:
  - name: Cpluz
    url: https://www.cpluz.com
  - name: Cpluz Accounts
    url: https://acc.cpluz.com
  - name: Z Accounts
    url: https://accounts.cpluz.com
  - name: S Accounts
    url: https://accounts.cpluz.in
  - name: Serverify
    url: https://serverify.in
  - name: Vasanthamdoors
    url: https://vasanthamdoors.com
  - name: Ispearexports
    url: https://ispearexports.com
  - name: Shrijayan
    url: https://shrijayan.cpluz.com
  - name: GPU Calculator
    url: https://calgpu.cpluz.com
  - name: Aameco
    url: https://aameco.in
  - name: Kingtraderss
    url: https://kingtraderss.com
  - name: Accounts Kingtraderss
    url: https://accounts.kingtraderss.com
  - name: Inventory Kingtraderss
    url: https://inventory.kingtraderss.com
  - name: Baseefy
    url: https://baseefy.com
  - name: Winnovin
    url: https://winnovin.com
  - name: Inventory Winnovin
    url: https://inventory.winnovin.com
  - name: Viyaanexport
    url: https://viyaanexport.com
  - name: Vihandesigns COM
    url: https://vihandesigns.com
  - name: Vihandesigns IN
    url: https://vihandesigns.in
  - name: Skyaloft
    url: https://skyaloft.com
  - name: Lunux
    url: https://lunux.in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: webcheck.cpluz.com
  baseUrl: /sitecheck
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
